# Generated by Django 3.0.8 on 2021-07-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=1, upload_to='images/users', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
