# Generated by Django 3.0.8 on 2021-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='yved',
            field=models.BooleanField(default=False, verbose_name='Уведомить'),
        ),
    ]
