# Generated by Django 3.2.5 on 2021-07-09 15:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='nameen',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contenten',
        ),
        migrations.RemoveField(
            model_name='post',
            name='titleen',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='nameen',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя рубрики(ru)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя рубрики(ru)'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание(ru)'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание(ru)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование(ru)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование(ru)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Название(ru)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название(ru)'),
        ),
    ]
