# Generated by Django 3.1.7 on 2021-07-19 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210718_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
