# Generated by Django 3.0.8 on 2021-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fed',
            name='yved',
            field=models.BooleanField(default=False, verbose_name='Уведомить'),
        ),
        migrations.AddField(
            model_name='reg',
            name='yved',
            field=models.BooleanField(default=False, verbose_name='Уведомить'),
        ),
        migrations.AlterField(
            model_name='fed',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='reg',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Наименование'),
        ),
    ]
