# Generated by Django 3.2.5 on 2021-07-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0005_auto_20210707_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fed',
            name='content',
        ),
        migrations.RemoveField(
            model_name='fed',
            name='contenten',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='content',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='contenten',
        ),
    ]
