# Generated by Django 3.2.5 on 2021-07-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0007_alter_fed_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fed',
            name='titleen',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='titleen',
        ),
        migrations.AlterField(
            model_name='fed',
            name='slug',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Ссылка'),
        ),
    ]
