# Generated by Django 3.2.5 on 2021-07-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konkurs', '0008_auto_20210708_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='slug',
            field=models.CharField(max_length=255, verbose_name='Ссылка'),
        ),
    ]
