# Generated by Django 3.0.8 on 2021-07-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0003_auto_20210711_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpemail',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtppassword',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpport',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpserver',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='workschedule',
        ),
    ]
