# Generated by Django 3.0.8 on 2021-07-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profsmena', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smena',
            options={'ordering': ['-created_at'], 'verbose_name': 'Профильная смена', 'verbose_name_plural': 'Профильная смена'},
        ),
    ]
