# Generated by Django 3.2.5 on 2021-07-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Заявки'},
        ),
    ]
