# Generated by Django 3.2.5 on 2021-07-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taski', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadacha',
            name='time',
            field=models.TimeField(default=0, verbose_name='Время просмотров'),
        ),
    ]
