# Generated by Django 3.2.5 on 2021-07-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taski', '0002_alter_zadacha_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vopros',
            name='zadacha',
            field=models.ManyToManyField(related_name='voprosiki', to='taski.Zadacha'),
        ),
    ]
