# Generated by Django 3.2.5 on 2021-07-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taski', '0003_vopros_zadacha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vopros',
            name='zadacha',
        ),
        migrations.AddField(
            model_name='vopros',
            name='zadacha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voprosiki', to='taski.zadacha'),
            preserve_default=False,
        ),
    ]
