# Generated by Django 2.2.2 on 2021-07-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taski', '0004_auto_20210718_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vopros',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vopros',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/', verbose_name='Изображение задачи'),
        ),
        migrations.AlterField(
            model_name='zadacha',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
