# Generated by Django 3.0.8 on 2021-07-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('glavnaya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Slidertitle', to='news.Post', verbose_name='Новость'),
        ),
    ]
