# Generated by Django 3.0.8 on 2021-07-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('glavnaya', '0003_vidjet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourites', models.ManyToManyField(related_name='favourites', to='news.Category', verbose_name='Список')),
            ],
            options={
                'verbose_name': 'Избранная категория',
                'verbose_name_plural': 'Избранные категорий',
            },
        ),
    ]
