# Generated by Django 3.0.8 on 2021-07-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0005_auto_20210711_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorit',
            options={'verbose_name': 'Ибранная категория', 'verbose_name_plural': 'Ибранная категория'},
        ),
    ]
