# Generated by Django 3.2.5 on 2021-07-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210707_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='problemen',
            field=models.TextField(default=1, max_length=255, verbose_name='Вопрос(EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='replyen',
            field=models.TextField(default=1, verbose_name='Ответ(EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='problem',
            field=models.TextField(max_length=255, verbose_name='Вопрос(RU)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='reply',
            field=models.TextField(verbose_name='Ответ(RU)'),
        ),
    ]
