# Generated by Django 3.0.8 on 2021-07-14 11:12

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuseris',
            name='region',
            field=models.CharField(default=1, max_length=30, verbose_name='Регион'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='userprofile.UserProfile', verbose_name='Родитель'),
        ),
    ]
