# Generated by Django 3.0.8 on 2021-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('userprofile', '0002_auto_20210714_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rubric',
            field=models.ManyToManyField(to='news.Category', verbose_name='Интересы'),
        ),
    ]
