# Generated by Django 3.0.8 on 2021-07-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210714_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='punk',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='punkt',
            field=models.CharField(choices=[('Ul', 'Ульяновск'), ('Bar', 'Барыш')], default='Ul', max_length=30, verbose_name='Населеный пункт'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Maim', 'Мужчина'), ('Woman', 'Женщина')], default='Maim', max_length=30, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zaved',
            field=models.CharField(choices=[('Sc-1', 'Школа №1'), ('Sc-2', 'Школа №1')], max_length=30, verbose_name='Учебное заведение'),
        ),
    ]
