# Generated by Django 3.0.8 on 2021-07-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exsov',
            name='doljnost',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popsov',
            name='doljnost',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
