# Generated by Django 3.2.5 on 2021-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exsov',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='exsov',
            name='status',
            field=models.CharField(choices=[('Publish', 'Опубликовать'), ('Not_to_publish', 'Не публиковать')], default='Publish', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='popsov',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/', verbose_name='Фото'),
        ),
    ]
