# Generated by Django 3.0.8 on 2021-07-11 04:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('smena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smena',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='smena',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='smena',
            name='title_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='smena',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='smena',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category', verbose_name='Рубрика'),
        ),
    ]
