# Generated by Django 3.0.8 on 2021-07-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smena', '0002_auto_20210711_0446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smena',
            options={'ordering': ['-created_at'], 'verbose_name': 'Профильная смена', 'verbose_name_plural': 'Профильные смены'},
        ),
    ]
