# Generated by Django 3.0.8 on 2021-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smena', '0003_auto_20210711_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='smena',
            name='yved',
            field=models.BooleanField(default=False, verbose_name='Уведомить'),
        ),
    ]
