# Generated by Django 3.2.5 on 2021-07-17 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20210717_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='Изображение')),
                ('punkt', models.CharField(choices=[('Ульяновск', (('sc-1', 'Школа №1'), ('sc-2', 'Школа №1'))), ('Барыш', (('sc-1', 'Школа №1'), ('sc-2', 'Школа №1'))), ('Димитровград', (('sc-1', 'Школа №1'), ('sc-2', 'Школа №1')))], max_length=30, verbose_name='Населеный пункт')),
                ('klass', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default=1, max_length=30, verbose_name='Класс')),
                ('dt', models.DateField(max_length=255, verbose_name='Дата рождения')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('ychenik', models.BooleanField(default=False, verbose_name='Ученик онлайн')),
                ('pol', models.CharField(choices=[('Maim', 'Мужчина'), ('Woman', 'Женщина')], max_length=30, verbose_name='Пол')),
                ('rubric', models.ManyToManyField(blank=True, to='news.Category', verbose_name='Интересы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
