# Generated by Django 3.2.5 on 2021-07-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akaynt', '0003_auto_20210717_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
