# Generated by Django 3.2.5 on 2021-07-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akaynt', '0004_alter_customer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
