# Generated by Django 3.2.5 on 2021-07-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akaynt', '0005_remove_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
