# Generated by Django 3.2.5 on 2021-07-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akaynt', '0006_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='klass',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default=1, max_length=30, verbose_name='Класс'),
        ),
    ]
